### ISSUE TITLE
literally can't get this to work

### ISSUE THREAD

**Issue by zombodotcom** [nomis51/Menagerie#12]
I have tried to use this since you first released it, put in my poessid and changed the leagues. Deleted the old versions and still nothing. 
Is there a setup step I am missing?

**Comment by nomis51** [comment]
The POESESSID is only required for the chaos recipe overlay, because it needs it to "see" what you have in your dedicated stash tab. Otherwise it's not required (By the way, when you enter your POESESSID, you need to restart the app. There are messages on screen for each setting that needs a restart).

When you say "still nothing", what's happening ? The overlay doesn't show up ? The app crash ? Can you provide more details and tell step by step what you're doing ?

Also, can you provide the log file of located in ``` C:\Users\<your name here>\AppData\Menagerie\app-<app version here>\logs\<date of the log file>.log``` related to your latest unsuccessfull try to use the app (relevant date), please. So I can see if something went wrong while using the app.

**Comment by nomis51** [comment]
It's been 18 days now, with no feedback, so I'm going to close this issue.
I suppose you don't use it anymore or you found a solution.
Feel free to re-open this issue and provide additional details if you experience problems again!
