### ISSUE TITLE
Application change windowstate of PathOfExile's window on start if display settings Mode=Windowed and maximized

### ISSUE THREAD

**Issue by XaocDIO** [nomis51/Menagerie#7]
Hi! 
I have a game running with the display mode "Windowed". The window is maximized. When I run your program, it collapses the game screen to its normal state.
The same thing happens when I press the buttons "Clear offers...".

**Comment by nomis51** [comment]
Thanks for the report, I'll take a look!

**Comment by nomis51** [comment]
Will be fixed in 1.2.13.

The app was "restoring" the state of the PoE window after bringing back PoE on top (after interacting with the overlay or when you start the app), which was causing the PoE window to go back to it's default state : Not maximized. Now, the app keeps the current state while focusing back to the game.
